### ISSUE TITLE
Error while trying to build docker

### ISSUE THREAD

**Issue by umbrella226** [ozolotareva/DESMOND2#2]
https://github.com/ozolotareva/DESMOND2/blob/6f53dc7df9eb9a0f15393fd1889a4dd49863676e/Dockerfile#L8

Directory mentioned in line COPY ./dist/ /app does not exist in the repository and causes build to fail.

**Comment by Freddsle** [comment]
@umbrella226 Thank you for noticing!
Added package .tar to the dist folder.  
If you find any other issues with Docker building, please let me know.
